### ISSUE TITLE
Make yii-swiftmailer this library's impementation

### ISSUE THREAD

**Issue by samdark** [yiisoft/mailer#1]
https://github.com/yiisoft/yii-swiftmailer should become implementation of this library.

**Comment by machour** [comment]
Are we talking about moving https://github.com/yiisoft/yii-core/blob/master/src/mail/MailerInterface.php here?

**Comment by samdark** [comment]
Yes.

**Comment by razonyang** [comment]
@samdark would you please submit mailer package to packagist :), so that I don't need to add repository into composer.json.

BTW, `yii-swiftmailer` is likely to remove `yii-core` dependency, what will the repository name and namespace  be? Or just stay the same?

**Comment by samdark** [comment]
Done.

**Comment by samdark** [comment]
Renamed mailer to https://github.com/yiisoft/mailer-swiftmailer
