### ISSUE TITLE
\Yii::$app->mailer->compose() and html body

### ISSUE THREAD

**Issue by sergey-program** [yiisoft/mailer#2]
When we call \Yii::$app->mailer->compose() it returns object. But i cannot somehow get the rendered html body. We can only set it.

Usages, for example we have x2 mail sending types, native (our server smtp and swirftmail) and some other service (api, curl). I want to render data as html and send it. But when I try ->compose() it returns object and I cannot get html or text from it.

Any solutions?

**Comment by tomaszkane** [comment]
I can provide code to handle `getTextBody()` and `getHtmlBody()`.
