### ISSUE TITLE
Make embedded files available in layout

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/mailer#25]
### What steps will reproduce the problem?
Embed a file.

```php
$file = File::fromPath('file.png', 'name.png', 'image/png');
$message = $this->mailer->compose('view', ['file' => $file])
    ->withEmbedded($file);
```

### What is the expected result?
Embbed files are available in view and layout (html).

### What do you get instead?
Embbed files are available in view only.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | @dev
| PHP version      | 8.0.1
| Operating system |

**Comment by samdark** [comment]
Why do you need embedded files in layout? Do you have a common image there such as company logo?

**Comment by Mister-42** [comment]
> Why do you need embedded files in layout? Do you have a common image there such as company logo?

I think a company logo in footers is quite common indeed.
