### ISSUE TITLE
View is called incorrectly

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/mailer#30]
### What steps will reproduce the problem?
```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Yiisoft\Mailer\MailerInterface;

class Test extends Command
{
    private MailerInterface $mailer;

    public function __construct(MailerInterface $mailer)
    {
        $this->mailer = $mailer;
        parent::__construct();
    }
}
```

I tried a lot of options I use in my project, and found `MailerInterface` to be causing the error below.

`./vendor/bin/yii`

### What do you get?
```
In View.php line 117:
                                                                                                                     
  Yiisoft\View\View::__construct(): Argument #1 ($basePath) must be of type string, null given, called in /yii-demo/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php on line 36
  ```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 8.0.2
| Operating system | Debian 10

**Comment by devanych** [comment]
The mailer has recently been updated, another class `MessageBodyTemplate` has been added, have you updated the dependencies?

**Comment by Mister-42** [comment]
Above was tried on a fresh yii-demo install, full update.

**Comment by devanych** [comment]
Ok. I'll take a look.

**Comment by devanych** [comment]
It's just not clear where the error is. In your example, the problem is with `Yiisoft\View\View`. Could you show a detailed stacktrace?

**Comment by Mister-42** [comment]
I just closed my laptop for the night, sorry. The example could give you all you need. Copy/ paste into yii/demo, add to params for console commands and run vendor/bin/yii

**Comment by Mister-42** [comment]
I can't for the life of me manage to get a stacktrace in console :rage: I want to help, but am kinda failing right now

**Comment by devanych** [comment]
It's not the mailer's problem if I do this:

```php
use Symfony\Component\Console\Command\Command;
use Yiisoft\View\WebView;

class Test extends Command
{
    private WebView $view;

    public function __construct(WebView $view)
    {
        $this->view = $view;
        parent::__construct();
    }
}
```

And run it `./vendor/bin/yii`, I get exactly the same error:

```
In View.php line 117:

Argument 1 passed to Yiisoft\View\View::__construct() must be of the type string, null given, called in /home/devanych/work/yii-demo/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php on line 36
```

**Comment by devanych** [comment]
Apparently, the `Yiisoft\View\View` is defined only for the WEB config, and it is not in the console config.

**Comment by Mister-42** [comment]
> Apparently, the `Yiisoft\View\View` is defined only for the WEB config, and it is not in the console config.

I _thought_ I had covered that and ruled it out... but I am wrong.. Sorry about that.

So I guess closing this Issue and create a new one on View?

**Comment by devanych** [comment]
Need to make it work to understand the reason, and then open the issue. :)

**Comment by Mister-42** [comment]
https://github.com/yiisoft/view/blob/master/config/console.php should be alright..?

**Comment by terabytesoftw** [comment]
https://github.com/yiisoft/mailer-swiftmailer/blob/70ae13473a004ddfcaed4fa9c7c69c9a3b9cf647/config/common.php#L23

**Comment by Mister-42** [comment]
> https://github.com/yiisoft/mailer-swiftmailer/blob/70ae13473a004ddfcaed4fa9c7c69c9a3b9cf647/config/common.php#L23

Nice catch! Webview in console is not an option indeed.

**Comment by devanych** [comment]
Changed to View, same error. :(

**Comment by devanych** [comment]
And not the same, different :)
